server:
  port: 8007
  
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: warmer.star.entity    # 所有Entity别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件
    
spring:
   application:
    name: warmercloud-blog
   datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://118.31.43.234:3306/warmerblog?useSSL=false             # 数据库名称
    username: tan
    password: 123456
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间
#在 spring boot 升为 2.0 后，为了安全，默认 Actuator 只暴露了2个端点，heath 和 info 
#下面配置是用来暴露 Actuator 的所有端点的，这一点很重要，不配置你的 Hystrix Dashboard 会出现 Unable to connect to Command Metric Stream 的问题
management:
  endpoints:
    web:
      exposure:
        include: "*"   
  endpoint:
      health:
        show-details: ALWAYS      
eureka:
  client: #客户端注册进eureka服务列表内
    service-url: 
      #defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: warmercloud-blog-hystrix-8007
    prefer-ip-address: true     #访问路径可以显示IP地址    
    
info: 
  app.name: warmer-cloud
  company.name: tan
  build.artifactId: $project.artifactId$
  build.version: $project.version$

